### PR TITLE
RA-1797 Correct UUID value in Reference Demo Data Module

### PR DESCRIPTION
**Pull request by Am-Coder**
**Changes I made**
Corrected UUID value by trimming extra e.

**Link to ticket**
https://issues.openmrs.org/browse/RA-1797

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you see the travis build failure?

**Comment by Am-Coder** [comment]
@dkayiwa , I have ran tests on my system and all tests are passing. I am not able to get the reason why travis is failing from fail logs.

**Comment by Am-Coder** [comment]
Travis Logs are showing : 

```
Installing oraclejdk8

$ export JAVA_HOME=~/oraclejdk8

$ export PATH="$JAVA_HOME/bin:$PATH"

$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"

Ignoring license option: BCL -- using GPLv2+CE by default

install-jdk.sh 2020-06-02

Expected feature release number in range of 9 to 16, but got: 8

The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

Your build has been stopped.
```

**Comment by dkayiwa** [comment]
Can you change it from oraclejdk to openjdk?

**Comment by Am-Coder** [comment]
> Can you change it from oraclejdk to openjdk?

Changed it to openjdk8

**Pull request merged**
