### PR TITLE
RA-2022: Fix test failure on Bamboo CI

### PR DESCRIPTION
**Pull request by Ruhanga**
This is a followup commit to fix bamboo failing tests. Couldn't reproduce the test failures locally.

Ticket: https://issues.openmrs.org/browse/RA-2022

### CODE REVIEW

**Review by ibacher — APPROVED** [review]

**Comment by dkayiwa** [comment]
@Ruhanga does this branch of the reference demo data module still respect the `referencedemodata.createDemoPatientsOnNextStartup` global property? As in, does it actually generate those patients?

**Comment by Ruhanga** [comment]
Yes @dkayiwa. This is happening [here](https://github.com/openmrs/openmrs-module-referencedemodata/blob/2.x/api/src/main/java/org/openmrs/module/referencedemodata/ReferenceDemoDataActivator.java#L81).

**Comment by dkayiwa** [comment]
I have restarted, set that value again, still not demo patients created on restart. I just haven't looked into why.

**Comment by Ruhanga** [comment]
On top of some [artefact requirements](https://github.com/openmrs/openmrs-module-referencedemodata/blob/2.x/omod/src/main/resources/config.xml), some metadata is required as well. You probably want to load [the configs](https://github.com/openmrs/openmrs-distro-referenceapplication/tree/main/distro/configuration) that come with Ref App 3.x

**Comment by dkayiwa** [comment]
I used the latest snapshot version of the sdk `org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:4.6.0-SNAPSHOT:setup` which automatically loads the configuration metadata.

**Comment by Ruhanga** [comment]
This scenario definitely requires making use of some console logs. Could there be some traces/logs to share?

**Comment by dkayiwa** [comment]
Actually you could be right. I checked the configuration folder, it has some metadata but not all. Let me fix that.

**Pull request merged**
